### ISSUE TITLE
2020.1.18版本出现了表格上的报错，之前的版本没问题

### ISSUE THREAD

**Issue by freechen** [jin-yufeng/Parser#77]
**问题描述**  
VM517:1 thirdScriptError
Cannot read property 'length' of undefined; [Component] Property Observer Error @ components/Parser/index#observer
TypeError: Cannot read property 'length' of undefined
    at _setBorder (http://127.0.0.1:12464/appservice/components/Parser/libs/MpHtmlParser.js:240:38)
    at _setBorder (http://127.0.0.1:12464/appservice/components/Parser/libs/MpHtmlParser.js:241:13)
    at MpHtmlParser.popNode (http://127.0.0.1:12464/appservice/components/Parser/libs/MpHtmlParser.js:249:11)
    at MpHtmlParser.EndTag (http://127.0.0.1:12464/appservice/components/Parser/libs/MpHtmlParser.js:378:18)
    at MpHtmlParser.parse (http://127.0.0.1:12464/appservice/components/Parser/libs/MpHtmlParser.js:58:14)
    at parseHtmlSync (http://127.0.0.1:12464/appservice/components/Parser/libs/MpHtmlParser.js:404:44)
    at be.setContent (http://127.0.0.1:12464/appservice/components/Parser/index.js:180:28)
    at be.observer (http://127.0.0.1:12464/appservice/components/Parser/index.js:50:14)
    at Function.r.safeCallback (http://127.0.0.1:12464/appservice/__dev__/WAService.js:1:1312285)
    at n.<anonymous> (http://127.0.0.1:12464/appservice/__dev__/WAService.js:1:1403915)

![image](https://user-images.githubusercontent.com/5688949/72676429-0e8bbe00-3acc-11ea-8450-4bb6a2f04986.png)

**Comment by jin-yufeng** [comment]
提供一下 `html`

**Comment by freechen** [comment]
`<table cellpadding="0" cellspacing="0" width="1005" height="341" style="width: 946px;">
<colgroup>
<col width="118" style="width:118px">
<col width="217" style="width:217px">
<col width="199" style="width:199px">
<col width="289" style="width:289px">
<col width="182" style="width:182px">
</colgroup>
<tbody>
<tr height="34" style="height:34px" class="firstRow">
<td rowspan="2" height="68" width="118" x:str="" style="">时  间</td>
<td colspan="2" width="416" x:str="" style="border-right: 1px solid rgb(0, 0, 0);">值班</td>
<td rowspan="2" width="289" x:str="" style="">联系电话</td>
<td rowspan="2" width="182" x:str="" style="">地点</td>
</tr>
<tr height="34" style="height:34px">
<td x:str="">本</td>
<td x:str="">南</td>
</tr>
<tr height="32" style="height:32px">
<td height="32" x:str="" style="">1月15日-19日</td>
<td x:str="">某某、某某、某某</td>
<td x:str="">某某、某某</td>
<td x:str="">111、2222、2222</td>
<td rowspan="5" x:str="">值班室</td>
</tr>
<tr height="32" style="height:32px">
<td height="32" x:str="" style="">1月20日-24日</td>
<td x:str="">某某、某某、某某</td>
<td x:str="">某某、某某</td>
<td x:str="">122、222、22</td>
</tr>

<tr height="113" style="height:113px"><td colspan="5" height="113" width="1005" x:str="" style="">值班要求：1、各位值班人。</td></tr>
</tbody>
</table>
<p><br></p>`

**Comment by jin-yufeng** [comment]
已修复
